"""Update celery_task_executions table indexes

Revision ID: 2bd12603115c
Revises: 49b0006556a1
Create Date: 2025-12-04 10:18:55.468611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd12603115c'
down_revision: Union[str, Sequence[str], None] = '49b0006556a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_task_name_args_celery_hash', 'celery_task_executions', ['task_name', 'task_args_hash', 'celery_task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_name_args_celery_hash', table_name='celery_task_executions')
    # ### end Alembic commands ###
