"""create celery task execution

Revision ID: 49b0006556a1
Revises: 7b2db7962fe9
Create Date: 2025-12-04 08:53:39.859548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49b0006556a1'
down_revision: Union[str, Sequence[str], None] = '7b2db7962fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_task_executions',
    sa.Column('execution_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('task_args_hash', sa.String(length=64), nullable=False),
    sa.Column('celery_task_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('task_args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index('ix_celery_task_id', 'celery_task_executions', ['celery_task_id'], unique=False)
    op.create_index('ix_task_executtion_created_at', 'celery_task_executions', ['created_at'], unique=False)
    op.create_index('ix_task_executtion_status', 'celery_task_executions', ['status'], unique=False)
    op.create_index('ix_task_name_args_hash', 'celery_task_executions', ['task_name', 'task_args_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_name_args_hash', table_name='celery_task_executions')
    op.drop_index('ix_task_executtion_status', table_name='celery_task_executions')
    op.drop_index('ix_task_executtion_created_at', table_name='celery_task_executions')
    op.drop_index('ix_celery_task_id', table_name='celery_task_executions')
    op.drop_table('celery_task_executions')
    # ### end Alembic commands ###
