"""create celery task execution

Revision ID: 7b2db7962fe9
Revises: d6668b885024
Create Date: 2025-12-04 08:49:54.971745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b2db7962fe9'
down_revision: Union[str, Sequence[str], None] = 'd6668b885024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pgvectorcollection_1024_10')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pgvectorcollection_1024_10',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('pgvectorcollection_1024_10_chunk_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pgvectorcollection_1024_10_pkey'))
    )
    # ### end Alembic commands ###
